apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "backend.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels: {{ include "backend.commonLabels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.persistentVolume.annotations }}
  {{- $annotations := merge (.Values.commonAnnotations | default dict) (.Values.persistentVolume.annotations | default dict) }}
  annotations: {{ toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
    accessModes:
      - {{ .Values.persistentVolume.accessModes | first }}
    resources:
      requests:
        storage: {{ .Values.persistentVolume.size }}
    storageClassName: {{ .Values.persistentVolume.className | default "local-path" }}