apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{ include "backend.commonLabels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.secrets.annotations }}
  {{- $annotations := merge (.Values.commonAnnotations | default dict) (.Values.secrets.annotations | default dict) }}
  annotations: {{ toYaml $annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}