{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "frontend.fullname" . }}-hpa
  namespace: {{ .Release.Namespace }}
  labels: {{ include "frontend.commonLabels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.autoscaling.annotations }}
  {{- $annotations := merge (.Values.commonAnnotations | default dict) (.Values.autoscaling.annotations | default dict) }}
  annotations: {{ toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "frontend.fullname" . }}-deploy
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemory }}
    {{- end }}
  {{- if .Values.autoscaling.behavior }}
  behavior: {{- toYaml .Values.autoscaling.behavior | nindent 4 -}}
  {{- end }}
{{- end }}