apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-migrations-pvc
  namespace: microservice-manifests
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi