kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.26.6
  - role: worker
    image: kindest/node:v1.26.6
    labels:
      app: ingress-nginx
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
    image: kindest/node:v1.26.6
  - role: worker
    image: kindest/node:v1.26.6
  - role: worker
    image: kindest/node:v1.26.6
networking:
  disableDefaultCNI: true
  podSubnet: "192.168.0.0/16"
