apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: microservice-manifests
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: microservice-app
    app.kubernetes.io/managed-by: kubectl
  annotations:
    kubernetes.io/description: "PVC for PostgreSQL data storage"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: microservice-manifests
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: microservice-app
    app.kubernetes.io/managed-by: kubectl
  annotations:
    kubernetes.io/description: "PVC for backend application data storage"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
