apiVersion: v1
kind: ServiceAccount
metadata:
  name:  auditor
  namespace: microservice-manifests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservice-manifests-viewer
  namespace: microservice-manifests
subjects:
- kind: ServiceAccount
  name: auditor
  namespace: microservice-manifests
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
