apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default
  namespace: exercise-02
  labels:
    app: nginx-default
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name _;

      location /health {
        auth_basic off;
        return 200;
      }

      location / {
        auth_basic "Basic Authentication";
        auth_basic_user_file /etc/nginx/conf.d/.htpasswd;

        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
      }
    }
