apiVersion: v1
kind: Pod
metadata:
  name: "nginx"
  namespace: exercise-02
  labels:
    app: "nginx"
    app.kubernetes.io/name: "nginx"
    app.kubernetes.io/part-of: "exercise-02"
    app.kubernetes.io/component: "frontend"
  annotations:
    kubernetes-learning.io/developer-login: "andrey.stryukov"
    kubernetes-learning.io/exercise: "02"
spec:
  containers:
    - name: nginx
      image: "nginx:1.25-alpine"
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
          ephemeral-storage: "0.5Gi"
        limits:
          cpu: 200m
          memory: 500Mi
          ephemeral-storage: "1Gi"
      ports:
        - containerPort: 80
          name: http
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 80
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      livenessProbe:
        failureThreshold: 3
        tcpSocket:
          port: 80
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
      volumeMounts:
        - name: nginx-configs
          mountPath: "/etc/nginx/conf.d"
          readOnly: true
  automountServiceAccountToken: false
  restartPolicy: Always
  volumes:
    - name: nginx-configs
      projected:
        sources:
          - configMap:
              name: nginx-default
              items:
                - key: default.conf
                  path: default.conf
          - secret:
              name: nginx-creds
              items:
                - key: .htpasswd
                  path: .htpasswd
